// Keeps the customized Live Activity view and native tweaks in the repo.
//
// The widget view is generated by `expo-live-activity` during prebuild, and `ios/` is
// gitignored, so edits to the generated files would be lost. This plugin:
//   1. copies our tracked `plugins/liveActivity/LiveActivityView.swift` over the
//      generated widget view (and over the library's template) after prebuild;
//   2. passes the system's `context.isStale` into that view;
//   3. sets a `staleDate` on the native module so iOS can age the activity (and the
//      widget can show it is no longer live) when the app stops updating it — for
//      example while the app is suspended or the Mac is unreachable.
const { withDangerousMod } = require("@expo/config-plugins")
const fs = require("fs")
const path = require("path")

const CUSTOM_VIEW = path.join(__dirname, "liveActivity", "LiveActivityView.swift")

// After this many seconds without an app update, iOS marks the activity stale.
// Foreground updates land well inside this window; background/suspended apps and a
// lost Mac do not, which is exactly when the activity should read as not live.
const STALE_AFTER_SECONDS = 60

const WIDGET_FROM = "LiveActivityView(contentState: context.state, attributes: context.attributes)"
const WIDGET_TO =
  "LiveActivityView(contentState: context.state, attributes: context.attributes, isStale: context.isStale)"

function patchWidget(source) {
  if (source.includes(WIDGET_TO)) return source
  return source.replace(WIDGET_FROM, WIDGET_TO)
}

function patchModule(source) {
  return source.replace(/staleDate: nil/g, `staleDate: Date().addingTimeInterval(${STALE_AFTER_SECONDS})`)
}

function writeIfExists(file, transform) {
  if (!fs.existsSync(file)) return
  const source = fs.readFileSync(file, "utf8")
  const next = transform(source)
  if (next !== source) fs.writeFileSync(file, next)
}

function withLiveActivityView(config) {
  return withDangerousMod(config, [
    "ios",
    async (cfg) => {
      const iosRoot = cfg.modRequest.platformProjectRoot
      const projectRoot = cfg.modRequest.projectRoot
      const source = fs.readFileSync(CUSTOM_VIEW)

      // 1. Custom widget view: the generated target and the library template.
      const generated = path.join(iosRoot, "LiveActivity", "LiveActivityView.swift")
      if (fs.existsSync(path.dirname(generated))) fs.writeFileSync(generated, source)

      const template = path.join(projectRoot, "node_modules", "expo-live-activity", "ios-files", "LiveActivityView.swift")
      if (fs.existsSync(template)) fs.writeFileSync(template, source)

      // 2. Feed the system's stale flag into the view.
      writeIfExists(path.join(iosRoot, "LiveActivity", "LiveActivityWidget.swift"), patchWidget)
      writeIfExists(
        path.join(projectRoot, "node_modules", "expo-live-activity", "ios-files", "LiveActivityWidget.swift"),
        patchWidget,
      )

      // 3. Set a staleDate so iOS can age the activity without an app update.
      writeIfExists(
        path.join(projectRoot, "node_modules", "expo-live-activity", "ios", "ExpoLiveActivityModule.swift"),
        patchModule,
      )

      return cfg
    },
  ])
}

module.exports = withLiveActivityView
