// Keeps the customized Live Activity view in the repo.
//
// The widget view is generated by `expo-live-activity` during prebuild, and `ios/` is
// gitignored, so edits to the generated file would be lost. This plugin copies our
// tracked `plugins/liveActivity/LiveActivityView.swift` over the generated widget view
// (and over the library's template) after prebuild.
const { withDangerousMod } = require("@expo/config-plugins")
const fs = require("fs")
const path = require("path")

const CUSTOM_VIEW = path.join(__dirname, "liveActivity", "LiveActivityView.swift")

function withLiveActivityView(config) {
  return withDangerousMod(config, [
    "ios",
    async (cfg) => {
      const iosRoot = cfg.modRequest.platformProjectRoot
      const projectRoot = cfg.modRequest.projectRoot
      const source = fs.readFileSync(CUSTOM_VIEW)

      const generated = path.join(iosRoot, "LiveActivity", "LiveActivityView.swift")
      if (fs.existsSync(path.dirname(generated))) fs.writeFileSync(generated, source)

      const template = path.join(projectRoot, "node_modules", "expo-live-activity", "ios-files", "LiveActivityView.swift")
      if (fs.existsSync(template)) fs.writeFileSync(template, source)

      return cfg
    },
  ])
}

module.exports = withLiveActivityView
