import { StyleSheet } from "react-native"
import type { Theme } from "./theme"

export type Styles = ReturnType<typeof createStyles>

export function createStyles(t: Theme) {
  return StyleSheet.create({
    root: { flex: 1 },
    content: { padding: 20, paddingTop: 72, paddingBottom: 48 },
    headerRow: { flexDirection: "row", alignItems: "center", justifyContent: "space-between" },
    headerLinks: { flexDirection: "row", alignItems: "center", gap: 16 },
    emptyCard: { backgroundColor: t.surface, borderWidth: 1, borderColor: t.border, borderRadius: 16, padding: 20, gap: 10, alignItems: "flex-start" },
    emptyHint: { fontSize: 13, color: t.textMuted, marginBottom: 4 },
    brandRow: { flexDirection: "row", alignItems: "center", gap: 10, flexShrink: 1 },
    title: { fontSize: 22, fontWeight: "700", color: t.text, letterSpacing: -0.4 },
    settingsLink: { fontSize: 15, color: t.accent, fontWeight: "600" },
    statusPill: { flexDirection: "row", alignItems: "center", gap: 8, marginTop: 14, alignSelf: "flex-start", backgroundColor: t.badgeBg, paddingHorizontal: 12, paddingVertical: 6, borderRadius: 999 },
    statusText: { fontSize: 13, color: t.textSecondary },
    error: { fontSize: 13, color: t.error, marginTop: 8 },
    heroWrap: { marginTop: 18, marginBottom: 6 },
    heroInner: { padding: 22, alignItems: "center" },
    heroCount: { fontSize: 56, fontWeight: "800", color: t.text, letterSpacing: -1.5 },
    heroLabel: { fontSize: 14, color: t.textSecondary, marginTop: -4, marginBottom: 14 },
    heroBreakdown: { flexDirection: "row", gap: 16, flexWrap: "wrap", justifyContent: "center" },
    heroBreakdownSecond: { marginTop: 8 },
    heroStat: { flexDirection: "row", alignItems: "center", gap: 6 },
    heroStatText: { fontSize: 13, color: t.textSecondary },
    connectBlock: { marginTop: 16 },
    hint: { fontSize: 13, color: t.textMuted, marginTop: 14, marginBottom: 6 },
    manualRow: { flexDirection: "row", alignItems: "center", gap: 8 },
    gradientButton: { paddingVertical: 12, paddingHorizontal: 20, borderRadius: 12, alignItems: "center", justifyContent: "center" },
    gradientButtonText: { color: "#ffffff", fontWeight: "700", fontSize: 15 },
    input: { flex: 1, borderWidth: 1, borderColor: t.inputBorder, borderRadius: 12, paddingHorizontal: 12, paddingVertical: 10, backgroundColor: t.inputBg, color: t.text },
    inputFull: { borderWidth: 1, borderColor: t.inputBorder, borderRadius: 12, paddingHorizontal: 12, paddingVertical: 10, backgroundColor: t.inputBg, color: t.text },
    fieldLabel: { fontSize: 15, fontWeight: "600", color: t.text, marginBottom: 6 },
    settingRow: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", marginBottom: 8 },
    settingLabel: { fontSize: 15, color: t.text },
    fieldDescription: { fontSize: 13, color: t.textMuted, marginTop: 6, lineHeight: 18 },
    segment: { flexDirection: "row", backgroundColor: t.badgeBg, borderRadius: 12, padding: 4, gap: 4 },
    segmentItem: { flex: 1 },
    segmentSelected: { paddingVertical: 9, borderRadius: 9, alignItems: "center" },
    segmentUnselected: { paddingVertical: 9, borderRadius: 9, alignItems: "center" },
    segmentText: { fontSize: 14, fontWeight: "600", color: t.textSecondary },
    segmentTextSelected: { fontSize: 14, fontWeight: "700", color: "#ffffff" },
    rowButton: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", backgroundColor: t.surface, borderWidth: 1, borderColor: t.border, borderRadius: 12, paddingHorizontal: 16, paddingVertical: 14 },
    rowButtonText: { fontSize: 15, color: t.text, fontWeight: "600" },
    chevron: { fontSize: 20, color: t.textMuted },
    about: { fontSize: 14, color: t.textSecondary, lineHeight: 20, marginBottom: 8 },
    section: { fontSize: 12, fontWeight: "700", color: t.textMuted, textTransform: "uppercase", letterSpacing: 0.8, marginTop: 26, marginBottom: 10 },
    empty: { fontSize: 14, color: t.textMuted },
    cardGap: { marginBottom: 12 },
    cardPad: { padding: 16 },
    sessionHeader: { flexDirection: "row", alignItems: "center", gap: 8 },
    sessionTitle: { flex: 1, fontSize: 15, fontWeight: "600", color: t.text },
    sessionPhase: { fontSize: 11, color: t.textSecondary, textTransform: "uppercase", letterSpacing: 0.5 },
    badges: { flexDirection: "row", flexWrap: "wrap", gap: 6, marginTop: 8 },
    badge: { fontSize: 12, color: t.badgeText, backgroundColor: t.badgeBg, borderRadius: 7, paddingHorizontal: 8, paddingVertical: 3, overflow: "hidden" },
    sessionActivity: { fontSize: 14, color: t.text, marginTop: 8, lineHeight: 19 },
    inlineGlow: { marginTop: 12, borderRadius: 12, shadowOffset: { width: 0, height: 0 }, shadowRadius: 14, shadowOpacity: 0.65, elevation: 8 },
    inlineGradient: { borderRadius: 12, padding: 12 },
    inlinePendingTitle: { fontSize: 15, fontWeight: "700" },
    inlinePendingBody: { fontSize: 14, marginTop: 2 },
    actions: { flexDirection: "row", flexWrap: "wrap", gap: 8, marginTop: 12 },
    actionInner: { paddingVertical: 9, paddingHorizontal: 18, borderRadius: 10 },
    actionText: { color: "#ffffff", fontWeight: "700", fontSize: 14 },
    questionBlock: { marginTop: 12 },
    freeformRow: { flexDirection: "row", alignItems: "flex-end", gap: 8, marginTop: 10 },
    freeformInput: { flex: 1, borderWidth: 1, borderColor: "rgba(255,255,255,0.35)", borderRadius: 10, paddingHorizontal: 12, paddingVertical: 9, color: "#ffffff", backgroundColor: "rgba(255,255,255,0.12)", minHeight: 40, maxHeight: 96, textAlignVertical: "top" },
    moreLink: { fontSize: 13, fontWeight: "600", color: t.accent, marginTop: 2 },
    activityBlock: { marginTop: 10, borderRadius: 12, padding: 12, backgroundColor: t.badgeBg, borderWidth: 1, borderColor: t.border },
    activityText: { fontSize: 14, color: t.text, lineHeight: 19 },
    demoBanner: { marginTop: 14, borderRadius: 12, padding: 12, backgroundColor: t.badgeBg, borderWidth: 1, borderColor: t.border },
    demoBannerText: { fontSize: 13, color: t.textSecondary, lineHeight: 18 },
    demoActions: { flexDirection: "row", flexWrap: "wrap", gap: 8 },
    link: { color: t.accent, textDecorationLine: "underline" },
    heroCountRow: { flexDirection: "row", alignItems: "center", gap: 12 },
    heroAdd: { width: 36, height: 36, borderRadius: 18, borderWidth: 1.5, alignItems: "center", justifyContent: "center" },
    heroAddText: { fontSize: 24, fontWeight: "700", lineHeight: 26 },
    metaRow: { flexDirection: "row", alignItems: "center", gap: 8, marginTop: 8 },
    metaChip: { fontSize: 12, color: t.textSecondary, backgroundColor: t.badgeBg, borderRadius: 8, paddingHorizontal: 8, paddingVertical: 3, overflow: "hidden" },
    stopButton: { borderRadius: 8, paddingHorizontal: 10, paddingVertical: 4, backgroundColor: t.deny },
    stopButtonText: { color: "#ffffff", fontWeight: "700", fontSize: 12 },
    closeButton: { fontSize: 22, color: t.textMuted, paddingHorizontal: 4, lineHeight: 22 },
    confirmBackdrop: { flex: 1, backgroundColor: "rgba(0,0,0,0.5)", alignItems: "center", justifyContent: "center", padding: 24 },
    confirmCard: { width: "100%", maxWidth: 420, borderRadius: 16, borderWidth: 1, padding: 20, gap: 12 },
    confirmTitle: { fontSize: 17, fontWeight: "700", color: t.text },
    confirmMessage: { fontSize: 14, color: t.textSecondary, lineHeight: 20 },
    confirmActions: { flexDirection: "row", justifyContent: "flex-end", gap: 8, marginTop: 4 },
    switcherScroll: { maxHeight: 360 },
    switcherItem: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", paddingVertical: 10, borderBottomWidth: 1, borderBottomColor: t.border },
    switcherItemText: { fontSize: 15, color: t.text },
    switcherCheck: { fontSize: 15, color: t.accent, fontWeight: "700" },
    sparkleWrap: { alignItems: "center", justifyContent: "center", width: 28, height: 28 },
    sparkleMain: { color: "#ffffff", fontSize: 22, lineHeight: 24, marginTop: 2 },
    sparkleMini: { position: "absolute", top: -1, right: -2, color: "rgba(255,255,255,0.95)", fontSize: 11, lineHeight: 12 },
    cardTitle: { fontSize: 16, fontWeight: "700", color: t.text },
    cardBody: { fontSize: 14, color: t.textSecondary, marginTop: 4 },
  })
}
